import { mutation } from "./_generated/server";
import { v } from "convex/values";

export const seedTopStartups = mutation({
  args: {},
  handler: async (ctx) => {
    // Check if we already have top startups
    const existingTopStartups = await ctx.db
      .query("startups")
      .withIndex("by_top_startup", (q) => q.eq("isTopStartup", true))
      .collect();

    if (existingTopStartups.length > 0) {
      return { message: "Top startups already seeded" };
    }

    // Create a system user for seeding data
    const systemUser = await ctx.db
      .query("users")
      .filter((q) => q.eq(q.field("name"), "System"))
      .first();

    let systemUserId;
    if (!systemUser) {
      systemUserId = await ctx.db.insert("users", {
        name: "System",
        email: "system@startupdb.com",
      });
    } else {
      systemUserId = systemUser._id;
    }

    const topStartups = [
      {
        name: "OpenAI",
        description: "AI research and deployment company focused on ensuring artificial general intelligence benefits all of humanity.",
        website: "https://openai.com",
        category: "AI/ML",
        stage: "Series C",
        fundingAmount: 13000000000,
        foundedYear: 2015,
        location: "San Francisco, CA",
        employees: "501-1000",
        logoUrl: "https://upload.wikimedia.org/wikipedia/commons/4/4d/OpenAI_Logo.svg",
        tags: ["AI", "Machine Learning", "GPT", "Research"],
        valuation: 80000000000,
      },
      {
        name: "SpaceX",
        description: "Space exploration company designing, manufacturing and launching advanced rockets and spacecraft.",
        website: "https://spacex.com",
        category: "Transportation",
        stage: "Series D+",
        fundingAmount: 9500000000,
        foundedYear: 2002,
        location: "Hawthorne, CA",
        employees: "1000+",
        logoUrl: "https://upload.wikimedia.org/wikipedia/commons/d/de/SpaceX-Logo.svg",
        tags: ["Space", "Rockets", "Mars", "Satellites"],
        valuation: 180000000000,
      },
      {
        name: "Stripe",
        description: "Financial infrastructure platform for businesses to accept payments and manage their operations online.",
        website: "https://stripe.com",
        category: "Fintech",
        stage: "Series D+",
        fundingAmount: 2200000000,
        foundedYear: 2010,
        location: "San Francisco, CA",
        employees: "1000+",
        logoUrl: "https://upload.wikimedia.org/wikipedia/commons/b/ba/Stripe_Logo%2C_revised_2016.svg",
        tags: ["Payments", "API", "E-commerce", "Financial Services"],
        valuation: 95000000000,
      },
      {
        name: "Canva",
        description: "Online design platform that allows users to create social media graphics, presentations, posters and other visual content.",
        website: "https://canva.com",
        category: "Productivity",
        stage: "Series D+",
        fundingAmount: 572000000,
        foundedYear: 2012,
        location: "Sydney, Australia",
        employees: "1000+",
        logoUrl: "https://upload.wikimedia.org/wikipedia/commons/0/08/Canva_icon_2021.svg",
        tags: ["Design", "Graphics", "Templates", "Collaboration"],
        valuation: 40000000000,
      },
      {
        name: "Figma",
        description: "Collaborative web application for interface design with real-time collaboration features.",
        website: "https://figma.com",
        category: "Productivity",
        stage: "Acquired",
        fundingAmount: 333000000,
        foundedYear: 2012,
        location: "San Francisco, CA",
        employees: "501-1000",
        logoUrl: "https://upload.wikimedia.org/wikipedia/commons/3/33/Figma-logo.svg",
        tags: ["Design", "UI/UX", "Collaboration", "Prototyping"],
        valuation: 20000000000,
      },
      {
        name: "Notion",
        description: "All-in-one workspace that combines note-taking, project management, and collaboration tools.",
        website: "https://notion.so",
        category: "Productivity",
        stage: "Series C",
        fundingAmount: 343000000,
        foundedYear: 2016,
        location: "San Francisco, CA",
        employees: "201-500",
        logoUrl: "https://upload.wikimedia.org/wikipedia/commons/4/45/Notion_app_logo.png",
        tags: ["Productivity", "Notes", "Collaboration", "Workspace"],
        valuation: 10000000000,
      },
      {
        name: "Discord",
        description: "Voice, video and text communication service designed for creating communities.",
        website: "https://discord.com",
        category: "Social",
        stage: "Series H",
        fundingAmount: 995000000,
        foundedYear: 2012,
        location: "San Francisco, CA",
        employees: "501-1000",
        logoUrl: "https://assets-global.website-files.com/6257adef93867e50d84d30e2/636e0a6918e57475a843dcf5_icon_clyde_black_RGB.svg",
        tags: ["Gaming", "Communication", "Community", "Voice Chat"],
        valuation: 15000000000,
      },
      {
        name: "Databricks",
        description: "Unified analytics platform that accelerates innovation by unifying data science, engineering and business.",
        website: "https://databricks.com",
        category: "AI/ML",
        stage: "Series I",
        fundingAmount: 3500000000,
        foundedYear: 2013,
        location: "San Francisco, CA",
        employees: "1000+",
        logoUrl: "https://upload.wikimedia.org/wikipedia/commons/6/63/Databricks_Logo.png",
        tags: ["Big Data", "Analytics", "Machine Learning", "Cloud"],
        valuation: 43000000000,
      },
      {
        name: "Coinbase",
        description: "Cryptocurrency exchange platform that allows users to buy, sell, and store digital currencies.",
        website: "https://coinbase.com",
        category: "Blockchain",
        stage: "IPO",
        fundingAmount: 547000000,
        foundedYear: 2012,
        location: "San Francisco, CA",
        employees: "1000+",
        logoUrl: "https://upload.wikimedia.org/wikipedia/commons/1/1a/Coinbase_Logo.svg",
        tags: ["Cryptocurrency", "Exchange", "Bitcoin", "Blockchain"],
        valuation: 8000000000,
      },
      {
        name: "Airbnb",
        description: "Online marketplace for short-term homestays and experiences in various countries and regions.",
        website: "https://airbnb.com",
        category: "Real Estate",
        stage: "IPO",
        fundingAmount: 6400000000,
        foundedYear: 2008,
        location: "San Francisco, CA",
        employees: "1000+",
        logoUrl: "https://upload.wikimedia.org/wikipedia/commons/6/69/Airbnb_Logo_B%C3%A9lo.svg",
        tags: ["Travel", "Hospitality", "Marketplace", "Sharing Economy"],
        valuation: 75000000000,
      },
      {
        name: "Uber",
        description: "Ride-hailing service that connects riders with drivers through a mobile app.",
        website: "https://uber.com",
        category: "Transportation",
        stage: "IPO",
        fundingAmount: 25200000000,
        foundedYear: 2009,
        location: "San Francisco, CA",
        employees: "1000+",
        logoUrl: "https://upload.wikimedia.org/wikipedia/commons/c/cc/Uber_logo_2018.png",
        tags: ["Ride Sharing", "Transportation", "Mobility", "Gig Economy"],
        valuation: 93000000000,
      },
      {
        name: "Zoom",
        description: "Video communications platform that provides video conferencing, online meetings, and group messaging.",
        website: "https://zoom.us",
        category: "Productivity",
        stage: "IPO",
        fundingAmount: 161000000,
        foundedYear: 2011,
        location: "San Jose, CA",
        employees: "1000+",
        logoUrl: "https://upload.wikimedia.org/wikipedia/commons/7/7b/Zoom_Communications_Logo.svg",
        tags: ["Video Conferencing", "Remote Work", "Communication", "SaaS"],
        valuation: 16000000000,
      },
      {
        name: "Shopify",
        description: "E-commerce platform that allows individuals and businesses to create their own online stores.",
        website: "https://shopify.com",
        category: "E-commerce",
        stage: "IPO",
        fundingAmount: 122000000,
        foundedYear: 2006,
        location: "Ottawa, Canada",
        employees: "1000+",
        logoUrl: "https://upload.wikimedia.org/wikipedia/commons/0/0e/Shopify_logo_2018.svg",
        tags: ["E-commerce", "Online Store", "Retail", "SaaS"],
        valuation: 67000000000,
      },
      {
        name: "Palantir",
        description: "Big data analytics company that specializes in big data analytics and serves government and commercial clients.",
        website: "https://palantir.com",
        category: "AI/ML",
        stage: "IPO",
        fundingAmount: 2600000000,
        foundedYear: 2003,
        location: "Denver, CO",
        employees: "1000+",
        logoUrl: "https://upload.wikimedia.org/wikipedia/commons/6/65/Palantir_logo.svg",
        tags: ["Big Data", "Analytics", "Government", "Enterprise"],
        valuation: 16000000000,
      },
      {
        name: "Snowflake",
        description: "Cloud-based data warehousing company that provides a data cloud platform.",
        website: "https://snowflake.com",
        category: "SaaS",
        stage: "IPO",
        fundingAmount: 1400000000,
        foundedYear: 2012,
        location: "Bozeman, MT",
        employees: "1000+",
        logoUrl: "https://upload.wikimedia.org/wikipedia/commons/f/ff/Snowflake_Logo.svg",
        tags: ["Data Warehouse", "Cloud", "Analytics", "Enterprise"],
        valuation: 37000000000,
      },
      {
        name: "Instacart",
        description: "Grocery delivery and pick-up service that operates via a website and mobile app.",
        website: "https://instacart.com",
        category: "E-commerce",
        stage: "IPO",
        fundingAmount: 2700000000,
        foundedYear: 2012,
        location: "San Francisco, CA",
        employees: "1000+",
        logoUrl: "https://upload.wikimedia.org/wikipedia/commons/9/9f/Instacart_logo_and_wordmark.svg",
        tags: ["Grocery", "Delivery", "On-demand", "Marketplace"],
        valuation: 10000000000,
      },
      {
        name: "DoorDash",
        description: "Food delivery platform that connects customers with local restaurants and delivery drivers.",
        website: "https://doordash.com",
        category: "Food & Beverage",
        stage: "IPO",
        fundingAmount: 2500000000,
        foundedYear: 2013,
        location: "San Francisco, CA",
        employees: "1000+",
        logoUrl: "https://upload.wikimedia.org/wikipedia/commons/f/fe/DoorDash_logo.svg",
        tags: ["Food Delivery", "On-demand", "Marketplace", "Logistics"],
        valuation: 13000000000,
      },
      {
        name: "Robinhood",
        description: "Commission-free stock trading and investing app that democratizes access to financial markets.",
        website: "https://robinhood.com",
        category: "Fintech",
        stage: "IPO",
        fundingAmount: 5600000000,
        foundedYear: 2013,
        location: "Menlo Park, CA",
        employees: "1000+",
        logoUrl: "https://upload.wikimedia.org/wikipedia/commons/9/9c/Robinhood_logo.svg",
        tags: ["Stock Trading", "Investing", "Mobile App", "Commission-free"],
        valuation: 8000000000,
      },
      {
        name: "Peloton",
        description: "Exercise equipment and media company that provides indoor cycling and treadmill equipment with streaming fitness classes.",
        website: "https://onepeloton.com",
        category: "Healthcare",
        stage: "IPO",
        fundingAmount: 994000000,
        foundedYear: 2012,
        location: "New York, NY",
        employees: "1000+",
        logoUrl: "https://upload.wikimedia.org/wikipedia/commons/b/b8/Peloton_logo.svg",
        tags: ["Fitness", "Connected Devices", "Streaming", "Health"],
        valuation: 1500000000,
      },
      {
        name: "Rivian",
        description: "Electric vehicle manufacturer focused on electric trucks and delivery vans.",
        website: "https://rivian.com",
        category: "Transportation",
        stage: "IPO",
        fundingAmount: 12000000000,
        foundedYear: 2009,
        location: "Irvine, CA",
        employees: "1000+",
        logoUrl: "https://upload.wikimedia.org/wikipedia/commons/c/c4/Rivian_logo.svg",
        tags: ["Electric Vehicles", "Trucks", "Sustainability", "Automotive"],
        valuation: 12000000000,
      }
    ];

    // Insert the top startups
    for (const startup of topStartups) {
      await ctx.db.insert("startups", {
        ...startup,
        submittedBy: systemUserId,
        isTopStartup: true,
        totalInvestments: 0,
        investorCount: 0,
      });
    }

    return { message: `Successfully seeded ${topStartups.length} top startups` };
  },
});
